### PR TITLE
Move tests to module with Tests suffix.

### PR DESCRIPTION
**Pull request by gmilos**

### CODE REVIEW

**Comment by ddunbar** [comment]
LGTM, thanks!

**Comment by ddunbar** [comment]
Also fixed example-package-deckofplayingcards.

**Comment by gmilos** [comment]
@ddunbar Could you create a new tag too pls? (AFAIK there is no way for SwiftPM to pick up this new commit unless there is one)

**Comment by ddunbar** [comment]
... doing it as we speak ... done. Let me know if you see other issues...

**Comment by gmilos** [comment]
@ddunbar it all works now, just verified it.

**Pull request merged**
