### PR TITLE
Follow API Design Guidelines

### PR DESCRIPTION
**Pull request by an0**
https://swift.org/documentation/api-design-guidelines.html#be-grammatical

### CODE REVIEW

**Comment by gribozavr** [comment]
This LGTM, but https://github.com/apple/example-package-deckofplayingcards requires an update, too.

**Comment by kostiakoval** [comment]
the Examples needs to update as well
https://swift.org/package-manager/#example-usage

**Comment by masters3d** [comment]
@kostiakoval  Do you know if there is a place where to submit updates to the documentation on the website?

**Comment by kostiakoval** [comment]
no, I don't know :( Ask in mailing list. I think it's Apple private project

**Comment by masters3d** [comment]
I submitted a request: https://bugs.swift.org/browse/SR-1317

**Pull request merged**
